### ISSUE TITLE
記事詳細 | 画像をリンクにした際に表示が崩れる

### ISSUE THREAD

**Issue by luminus-xd** [microcmsio/nextjs-simple-blog-template#5]
microCMS templatesのサービスを利用させていただいており、その便利さに感謝しております！

新リッチエディタで画像にリンクを挿入した際に、`.content > figure > a > img`のHTML構造が生成されることに気づきました。
この構造のため、以下のCSS指定が適用されないようです。

```css
.content > figure > img {
  max-width: 100%;
  height: auto;
  margin: 2rem 0;
}
```
このCSSは、`.content > figure > img`の構造を想定しているように見受けられますが、リンクが挿入されるとその構造が変わるため、意図したスタイリングが適用されないと考えられます。

この問題がまだ把握されていない可能性があると思い、Issueを立てさせていただきました。
もし可能であれば、CSSを以下のように修正することで問題を解決できると思います。

```css
.content > figure > a > img,
.content > figure > img {
  max-width: 100%;
  height: auto;
  margin: 2rem 0;
}
```
この修正により、リンクが挿入された画像にも適切にスタイリングが適用されると考えます。

該当のCSSはこちらのリンクで確認できます：
https://github.com/microcmsio/nextjs-simple-blog-template/blob/main/components/Article/index.module.css#LL146C1-L150C2

以上、ご確認をお願いいたします。
